#!/usr/bin/env node
/**
 * Toggle the position paper full-text reader route on or off locally.
 *
 * Why a toggle instead of a route that is simply hidden:
 *
 *   - This repository is PUBLIC, and GitHub Pages builds from a fresh
 *     `actions/checkout`. Anything gitignored therefore cannot reach the
 *     deployed site at all — no HTML, and no paper text in the JS bundle.
 *   - SvelteKit only treats `+`-prefixed files as routes. With no
 *     `+page.svelte` under src/routes/position-paper/read/, the route does not
 *     exist, and nothing imports the reader code, so Rollup never bundles it.
 *
 * The reader's actual implementation lives in `src/lib/reader/` and
 * `src/lib/components/reader/` and IS committed — only the two route stubs
 * generated here (and the real draft markdown) stay out of git.
 *
 * Usage:
 *   node scripts/paper-reader.mjs on      # enable locally
 *   node scripts/paper-reader.mjs off     # disable
 *   node scripts/paper-reader.mjs status  # report current state
 */

import { existsSync, mkdirSync, writeFileSync, rmSync, copyFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const routeDir = resolve(root, 'src/routes/position-paper/read');
const pageSvelte = resolve(routeDir, '+page.svelte');
const pageTs = resolve(routeDir, '+page.ts');
const draftMd = resolve(root, 'src/lib/content/position-paper.md');
const exampleMd = resolve(root, 'src/lib/content/position-paper.example.md');

const BANNER = 'GENERATED by `npm run paper:on` — gitignored, do not commit.';

const PAGE_TS = `// ${BANNER}
import { loadPositionPaper } from '$lib/reader/load-paper';
import type { PageLoad } from './$types';

export const prerender = true;

export const load: PageLoad = () => loadPositionPaper();
`;

const PAGE_SVELTE = `<!-- ${BANNER} -->
<script lang="ts">
\timport PositionPaperReader from '$lib/components/reader/PositionPaperReader.svelte';
\timport type { PageData } from './$types';

\tinterface Props {
\t\tdata: PageData;
\t}

\tlet { data }: Props = $props();
</script>

<PositionPaperReader {data} />
`;

function enable() {
	mkdirSync(routeDir, { recursive: true });
	writeFileSync(pageTs, PAGE_TS, 'utf8');
	writeFileSync(pageSvelte, PAGE_SVELTE, 'utf8');
	console.log('Reader ENABLED  → /position-paper/read');

	if (!existsSync(draftMd)) {
		copyFileSync(exampleMd, draftMd);
		console.log('Seeded src/lib/content/position-paper.md from the example (gitignored).');
	}
	console.log('Edit src/lib/content/position-paper.md — it stays out of git.');
}

function disable() {
	if (existsSync(routeDir)) {
		rmSync(routeDir, { recursive: true, force: true });
	}
	console.log('Reader DISABLED → /position-paper/read will not be built.');
	console.log('Your draft at src/lib/content/position-paper.md is left untouched.');
}

function status() {
	const on = existsSync(pageSvelte);
	console.log(`Reader route : ${on ? 'ENABLED' : 'disabled'}`);
	console.log(`Draft file   : ${existsSync(draftMd) ? 'present' : 'absent (example used)'}`);
}

const command = process.argv[2];

switch (command) {
	case 'on':
		enable();
		break;
	case 'off':
		disable();
		break;
	case 'status':
		status();
		break;
	default:
		console.error(`Unknown command: ${command ?? '(none)'}\nUsage: paper-reader.mjs on|off|status`);
		process.exit(1);
}
